version: '1.0'

services:
  node_app:
    container_name: node_app
    build: .
    image: camirodev/node_api
    ports:
      - "5000:5000"
    environment:
      - PG_DB=node_api_db
      - PG_USER=camirodev
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db
    restart: always

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_api_db
      - POSTGRES_USER=camirodev
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}

